### ISSUE TITLE
Can't save weights.npz 

### ISSUE THREAD

**Issue by thanhtv96** [jihadbourassi/deep-anpr-for-Moroccan-licence-plates#1]
Help me pls !!! 
Error when Ctrl C
Traceback (most recent call last):
  File "train.py", line 276, in <module>
    initial_weights=initial_weights)
  File "train.py", line 243, in train
    test_xs, test_ys = unzip(list(read_data("test/*.png"))[:batch_size])
  File "train.py", line 69, in read_data
    im = cv2.imread(test)[:, :, 0].astype(numpy.float32)/255.0

**Comment by moxgeek** [comment]
i was having the same issus , but i figure out that when i pressed multitime on on Ctrl+C this error throwed , so please try Ctrl+C only one time  ,and wait .
